# This file was generated by GoReleaser. DO NOT EDIT.
class Password < Formula
  desc ""
  homepage ""
  version "0.8.2"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/foo/bar/releases/v0.8.2/password_0.8.2_Darwin_x86_64.tar.gz"
    sha256 "d439495081f4ab12f1aad4f9121a700d5781082dd47e8e4fc88d538a53fab019"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/foo/bar/releases/v0.8.2/password_0.8.2_Linux_x86_64.tar.gz"
      sha256 "7224b47a248deba22381f8779dd6932d2b88fa15a6ad528883708e6bc821071f"
    end
  end

  def install
    bin.install "password"
  end
end
